---
grails:
  profile: rest-api
  codegen:
    defaultPackage: rd.professional
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
  plugin:
    databasemigration:
      updateOnStart: true
      updateOnStartFileName: changelog.groovy
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---
grails:
  cors:
    enabled: true
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''

environments:
  development:
    dataSource:
      dbCreate: none
      url: jdbc:h2:file:~/.moj/db-rd-professional;AUTO_SERVER=TRUE;INIT=create domain if not exists jsonb as other;
      logSql: false
      formatSql: false
    server:
      port: 9000
    prd_users_endpointurl: http://localhost:9002
  test:
    dataSource:
      dbCreate: none
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;INIT=create domain if not exists jsonb as other;
  production:
    server:
      port: ${SERVER_PORT}
    prd_users_endpointurl: http://rd-user-profile-aat.service.core-compute-aat.internal
    dataSource:
      dbCreate: none
      url: ${SPRING_DATASOURCE_URL}
      driverClassName: org.postgresql.Driver
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: ${MAX_ACTIVE_DB_CONNECTIONS}
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY}

app-insights:
  dev-mode: off
  request-component: on
  telemetry-component: on